version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app/app
      - ./rust_core:/usr/src/app/rust_core
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/vegafs_dev"
      REDIS_URL: "redis://redis:6379"
      LOG_LEVEL: "INFO"
    depends_on:
      - db
      - redis
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: vegafs_dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pg_data: