apiVersion: v1
kind: ConfigMap
metadata:
  name: vegafs-config-staging
  namespace: vegafs-staging
data:
  DATABASE_URL: "postgresql://vegafs_user:vegafs_password@vegafs-db-staging:5432/vegafs_db"
  REDIS_URL: "redis://vegafs-redis-staging:6379"
  LOG_LEVEL: "INFO"