apiVersion: v1
kind: Service
metadata:
  name: vegafs-service
  labels:
    app: vegafs
spec:
  selector:
    app: vegafs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http
  type: ClusterIP